name: Android APK Bas
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sistem Kurulumu
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good libsqlite3-dev sqlite3 bzip2 libbz2-dev libssl-dev openssl libffi-dev libxcursor-dev libxinerama-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev autoconf automake libtool pkg-config ant ccache unzip
          pip install --user --upgrade buildozer cython==0.29.33
      - name: APK Hazirlama
        run: |
          buildozer init
          sed -i 's/title = My Application/title = Cepte Esnaf/' buildozer.spec
          sed -i 's/package.name = myapp/package.name = cepteesnaf/' buildozer.spec
          sed -i 's/source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py,png,jpg,kv,json/' buildozer.spec
          sed -i 's/requirements = python3,kivy/requirements = python3,kivy==2.2.1,firebase-admin,certifi,urllib3,requests/' buildozer.spec
          sed -i 's/#android.permissions = INTERNET/android.permissions = INTERNET/' buildozer.spec
          yes | buildozer -v android debug
      - name: APK Dosyasini Kaydet
        uses: actions/upload-artifact@v2
        with:
          name: CepteEsnaf-APK
          path: bin/*.apk
